### ISSUE TITLE
Incorrect computation of accessibility matrix

### ISSUE THREAD

**Issue by jacob-hastings** [TommasoBelluzzo/PyDTMC#11]
## Expected Behavior
The Markov chain with transition matrix `p = [[0. , 1. , 0. ], [1. , 0. , 0. ], [0. , 0.5, 0.5]]` has the accessibility matrix `[[1, 1, 0], [1, 1, 0], [1, 1, 1]]`.
## Current Behavior
The `accessibility_matrix` property returns the incorrect matrix `[[1, 1, 0], [1, 1, 0], [0, 1, 1]]`. Note the difference in the (2, 0) element.
## Steps to Reproduce
```
p = [[0. , 1. , 0. ], [1. , 0. , 0. ], [0. , 0.5, 0.5]]
mc = MarkovChain(p, ['A', 'B', 'C'])
print(mc.accessibility_matrix)
```
## Possible Solution
The computation of the accessibility matrix in the source code is incorrect. Specifically, the line `am = (i + a)**(self.__size - 1)` is incorrect. When applied to a NumPy array, ** is element-wise exponentiation, not true matrix exponentiation. To get matrix exponentiation, you should use `numpy.linalg.matrix_power()`:
`am = numpy.linalg.matrix_power(i + a, self.__size - 1)`

**Comment by TommasoBelluzzo** [comment]
The issue has been fixed in the new release.
Again, thanks for your help!
