### ISSUE TITLE
Incorrect `is_absorbing`

### ISSUE THREAD

**Issue by aadya940** [TommasoBelluzzo/PyDTMC#14]
![image](https://github.com/TommasoBelluzzo/PyDTMC/assets/77720426/5f3b579a-7106-4e0b-8be3-04d1976e4545)

How is this chain absorbing even though the only absorbing state is '3'. (Which is correct) but state '1' is not communicating with state '3'. In an absorbing markov chain, all states should be able to communicate with an absorbing state if I'm not wrong.

Thanks :-)

Hoping for a reply soon!

**Comment by TommasoBelluzzo** [comment]
Hi @aadya940.

By definition, an absorbing Markov chain is a Markov chain in which every state can reach an absorbing state.
When in S1, you can reach S1 or S2.
When in S2, you can reach S1, S2 or S3.
This means that from both S1 and S2 you can reach S3.
