### ISSUE TITLE
Version 8.2.0 removed?

### ISSUE THREAD

**Issue by Arepo** [TommasoBelluzzo/PyDTMC#15]
## Expected Behavior
My Streamlit app, which uses v8.2.0 should work (it was previously)

## Current Behavior
I get an error including the following

> [pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement pydtmc==8.2.0 (from versions: 0.1.2, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.6.0, 2.7.0, 2.8.0, 2.9.0, 3.0.0, 3.1.0, 3.2.0, 3.3.0, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.9.0, 4.0.0, 4.1.0, 4.2.0, 4.3.0, 4.4.0, 4.5.0, 4.6.0, 4.7.0, 4.8.0, 4.9.0, 5.0.0, 5.1.0, 5.2.0, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.8.0, 6.9.0, 6.10.0, 6.11.0, 7.0.0, 8.0.0, 8.7.0)
> 
> [pipenv.exceptions.InstallError]: ERROR: No matching distribution found for pydtmc==8.2.0
> 
> ERROR: Couldn't install package: {}
> 
>  Package installation failed...
> 
> /usr/local/lib/python3.10/subprocess.py:1072: ResourceWarning: subprocess 17 is still running
> 
>   _warn("subprocess %s is still running" % self.pid,
> 
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> 
> sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='utf-8'>
> 
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> 
> sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>
> 
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> 
> /mount/src/lrisk_calculator

## Steps to Reproduce
You can clone my app [here](https://github.com/Arepo/lrisk_calculator), and run it with `streamlit run Longtermist_Risk_Calculator.py`

**Comment by TommasoBelluzzo** [comment]
Hi @Arepo, sorry for the belated reply.
Yes, unfortunately, due to wrong package configs, there were errors in the latest releases that could prevent PyDTMC from running properly in some situations. Being unable to manually fix the releases, I had no choice.
Please, target the version 8.7.0 which is clean. Sorry for the inconvenience.
