### ISSUE TITLE
Output of plot_graph(mc) seems to have an overlapped figure

### ISSUE THREAD

**Issue by prof-amer** [TommasoBelluzzo/PyDTMC#6]
Whenever I call plot_graph(mc), it does output an image, but it seems like there is an overlapped empty figure as attached.

![image](https://user-images.githubusercontent.com/63526142/114051794-5475a300-9885-11eb-9e83-f616ea5727b1.png)

**Comment by ShubyM** [comment]
I have found a temporary workaround, the issue stems from the fact that matplotlib has axes enabled by default, so when it plots this figure those axes are still present and you can't see what's underneath.  So if you grab the output from pydtmc.plot_graph and then set axis to off you can fix the issue. Working off the example in the read me you can do

```python
 fig, ax = pydtmc.plot_graph(mc)
 ax.axis('off')
```

Then it should work as intended

Hope this helps!

**Comment by yagu0** [comment]
This fork applies the fix mentioned just above, and another one for plot_walk which was broken on plot_type='sequence' : https://github.com/yagu0/PyDTMC

**Comment by TommasoBelluzzo** [comment]
Hi all! Sorry for the belated reply. I released a new version on PyPI which includes the fixes made by @yagu0 (thank you very much for your contribution) and some more minor tweaks.

**Comment by yagu0** [comment]
Hi! Great, thank you!
I plan to use this module in a course with students uncomfortable with maths (not much above high-school level :/), so it will be very useful.

**Comment by TommasoBelluzzo** [comment]
Hi @yagu0, that's great! And I'm really glad this project can be helpful for you and your students.
Best wishes, Tommaso.
