### ISSUE TITLE
Graph output style is different compared to the old one in the examples given

### ISSUE THREAD

**Issue by prof-amer** [TommasoBelluzzo/PyDTMC#8]
Previously, when I called the plot_graph, it will output something like the example as so:
![past](https://user-images.githubusercontent.com/63526142/124049150-c3d7da80-da0f-11eb-936a-557595ca4661.png)

But now it is like this:
![current](https://user-images.githubusercontent.com/63526142/124049175-cf2b0600-da0f-11eb-9c45-68319de48dec.png)

Is there a way to revert to the old style?

**Comment by TommasoBelluzzo** [comment]
Hi @prof-amer! Do you have Graphviz and pydot installed?

**Comment by prof-amer** [comment]
Hi Tommaso! I did actually, that's why I'm confused why it suddenly became like this. I installed pydot from https://pypi.org/project/pydot/ and graphviz from here https://pypi.org/project/graphviz/.

**Comment by TommasoBelluzzo** [comment]
Glad this helped you!
