### ISSUE TITLE
Citation format

### ISSUE THREAD

**Issue by prof-amer** [TommasoBelluzzo/PyDTMC#9]
Hi @TommasoBelluzzo , since I am using this package for my master thesis, is there any specific format to cite this package? I found some way to format from the web:
1. https://www.wikihow.com/Cite-a-GitHub-Repository
2. https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository/referencing-and-citing-content
3. https://carpentries.topicbox.com/groups/discuss/T33d60669d32ac1d7/best-way-to-cite-github-repository

Let me know your thoughts.

**Comment by TommasoBelluzzo** [comment]
Hi @prof-amer, I'm really glad to hear you used my package for your thesis. I don't think there is a standard for GitHub citations, so feel free to use the format you prefer. Below, the format I usually employ:

> Tommaso Belluzzo (2019). PyDTMC (https://github.com/TommasoBelluzzo/PyDTMC), GitHub. Retrieved July 5, 2021.

If you are willing to provately share your work, I would be pleased to read your thesis.

Best,
Tommaso

**Comment by prof-amer** [comment]
Hi @TommasoBelluzzo, thank you for the suggestion! I would absolutely love to share my work. I will reach out to you once everything is settled and submitted. Currently writing the results part of the thesis, should be done in a few weeks.

Thank you again for the package and citation help!

Best,
Amer
